description = "Private registry for lab projects"
name = "LabRegistry"
repo = "https://github.com/haberdashPI/LabRegistry.jl"
uuid = "bb6984de-8c64-11e9-351b-43696c1a075b"

[packages]
7e25a372-ade5-11e8-17af-a30e5a9e2c28 = { name = "AuditoryBistabilityLE", path = "A/AuditoryBistabilityLE" }
80f90042-ac61-11e8-0ace-f1a8d5e03555 = { name = "ShammaModel", path = "S/ShammaModel" }
8b6f5f00-d239-11e8-3a24-33314b00f6b0 = { name = "PlotAxes", path = "P/PlotAxes" }
8fedaf65-873c-58d0-a124-d2a652e0e461 = { name = "Psychoacoustics", path = "P/Psychoacoustics" }
fcefd6c4-8de0-11e9-0d15-03bc7c8ec982 = { name = "LambdaFn", path = "L/LambdaFn" }
