description = "Private registry for lab projects"
name = "/Users/davidlittle/Documents/work/tools/LabRegistry"
repo = "https://github.com/haberdashPI/LabRegistry.jl"
uuid = "bb6984de-8c64-11e9-351b-43696c1a075b"

[packages]
80f90042-ac61-11e8-0ace-f1a8d5e03555 = { name = "ShammaModel", path = "S/ShammaModel" }
